In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices2.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: 'homeprices2.csv'

In [ ]:
#data preprocessing

In [9]:
df[["area"]]#data extracting

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [10]:
df[["price"]]#data extracting

price
0  550000
1  565000
2  610000
3  680000
4  725000

In [38]:
x = df[["area"]].values#csv to array
x

array([[2600],
       [3000],
       [3200],
       [3600],
       [4000]], dtype=int64)

In [16]:
y = df[["price"]].values#csv to array
y

array([[550000],
       [565000],
       [610000],
       [680000],
       [725000]], dtype=int64)

In [19]:
reg = linear_model.LinearRegression()#creating an object of the algorithm
reg

LinearRegression()

In [21]:
reg.fit(x, y)#training the data

LinearRegression()

In [25]:
reg.predict([[5000]])#predicting the y for the value of x = 5000

array([[859554.79452055]])

In [28]:
reg.intercept_

array([180616.43835616])

In [30]:
reg.coef_

array([[135.78767123]])

In [40]:
reg.score(x,y)#accuracy of the model: our model is 95% accurate

0.9584301138199486

ValueError: Expected 2D array, got scalar array instead:
array=859554.7945061601.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.