In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [26]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [67]:
#data preprocessing

In [27]:
median_bedrooms = df.bedrooms.median()#finding the median of bedrooms
median_bedrooms

4.0

In [28]:
df.bedrooms.fillna(median_bedrooms)#filling the nan variable

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [32]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)#filling the nan variable in main csv file
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [33]:
x = df[["area"]].values #data extracting

In [59]:
y = df[["bedrooms"]].values #data extracting
y

array([[3.],
       [4.],
       [4.],
       [3.],
       [5.],
       [6.]])

In [60]:
z = df[["age"]].values #data extracting

In [61]:
q = df[["price"]].values #data extracting
q

array([[550000],
       [565000],
       [610000],
       [595000],
       [760000],
       [810000]], dtype=int64)

In [62]:
reg = linear_model.LinearRegression() #creating an object of the algorithm
reg

LinearRegression()

In [63]:
X = np.column_stack((x,y,z)) #stacking all values in a single variable
Y = q

In [64]:
reg.fit(X,Y) #training the dataset
Y

array([[550000],
       [565000],
       [610000],
       [595000],
       [760000],
       [810000]], dtype=int64)

In [65]:
o = np.array([[5000,7,9]]) #predicting the values
reg.predict(o)

array([[916271.91094395]])

In [66]:
reg.score(X,Y) #accuracy of the model: our model is 95% accurate

0.9550196399325818