In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)


In [4]:
lr  = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

E:\Anaconda\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9555555555555556

In [6]:
svm  = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9814814814814815

In [13]:
rf =RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test,y_test)

0.9666666666666667

In [14]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [33]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test, y_test)

In [34]:
from sklearn.model_selection import StratifiedKFold

In [35]:
folds = StratifiedKFold(n_splits=3)

In [38]:
scores_l = []
scores_svm = []
scores_rf = []
for train_index, test_index in kf.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

In [39]:
scores_rf

[0.9348914858096828, 0.9632721202003339, 0.9282136894824707]

In [40]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [41]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [42]:
from sklearn.model_selection import cross_val_score

In [43]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])